ZubiArticleBundle_homepage:
    pattern:  /
    defaults: { _controller: ZubiArticleBundle:Default:index }
    
ZubiArticleBundle_showarticle:
    pattern:  /show/{id}
    defaults: { _controller: ZubiArticleBundle:Default:showArticle }
    
ZubiArticleBundle_add:
    pattern:  /add/
    defaults: { _controller: ZubiArticleBundle:Default:add }    
       
ZubiArticleBundle_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ZubiArticleBundle:Default:delete }        

ZubiArticleBundle_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ZubiArticleBundle:Default:edit }    
    
ZubiArticleBundle_groups:
    pattern:  /groups/
    defaults: { _controller: ZubiArticleBundle:Groups:index }    
        
ZubiArticleBundle_group_edit:
    pattern:  /groups/edit/{id}
    defaults: { _controller: ZubiArticleBundle:Groups:edit }    

ZubiArticleBundle_group_add: 
    pattern:  /groups/add/
    defaults: { _controller: ZubiArticleBundle:Groups:add }    

ZubiArticleBundle_group_delete:
    pattern:  /groups/delete/{id}
    defaults: { _controller: ZubiArticleBundle:Groups:delete }    

ZubiArticleBundle_author_add:
    pattern:  /author/add/{id}
    defaults: { _controller: ZubiArticleBundle:Author:add, id: 0 }   
   

