Zubi\ArticleBundle\Entity\Article:
  properties:
    title:
      - NotBlank: ~
    content:
      - NotBlank: ~
   
Zubi\ArticleBundle\Entity\ArticleGroup:
  properties:
    name:
      - NotBlank: ~
      
Zubi\UserBundle\Entity\Osoba:      
  properties:
    imie:
      - NotBlank: ~
    nazwisko:
      - NotBlank: ~
      